### ISSUE TITLE
Using the action 'authenticate' to add a recaptcha checkbox to other forms

### ISSUE THREAD

**Issue by miguelitomola** [cyberscribe/login-recaptcha#11]
Hi cyberscribe,

I was trying to add a recaptcha field in both, the woocommerce registration form and the woocommerce lost password form. I could add those fields with these lines in the [`action_plugins_loaded` function](https://github.com/cyberscribe/login-recaptcha/blob/ea54d0753521cea5d12e450419690e8ad5360b4b/login-nocaptcha.php#L38):

    add_action('woocommerce_register_form',array('LoginNocaptcha', 'nocaptcha_form'));
    add_action('woocommerce_lostpassword_form',array('LoginNocaptcha', 'nocaptcha_form'));

However the `authenticate` action is not being fired when submitting those forms, so the `authenticate` function is not called. I have been trying to understand how the `authenticate` action is fired in the login form, but I cannot find any `do_action('authenticate'...` in the code. Could you give me a hint about it, so I can implement those checkboxes?

Thanks

**Comment by cyberscribe** [comment]
`add_action('authenticate'...` is on line 33 of login-nocaptcha.php

**Comment by miguelitomola** [comment]
I couldn't find it. Sorry and thank you!
