### ISSUE TITLE
SOLVED* Could not get it work

### ISSUE THREAD

**Issue by MichaelPfleger** [cyberscribe/login-recaptcha#13]
I followed the instuctions and created the site keys here

https://www.google.com/recaptcha/admin/site/345****836/setup

and got this message:

ERROR for site owner: Invalid site key
Privacy - Terms

Sorry for not more info, i am not a dev,

KR

**Comment by cyberscribe** [comment]
This message from Google indicates you have not copied the full keys correctly.

**Comment by MichaelPfleger** [comment]
Hello,

i thought the same but tried it again (and made sure that i did the Copy&Paste correctly :) )
and the error message still apperas..

Is it possible that it does not work because the admin Email within Wordpress is not the same as my G-Mail Account for Google Dev?

**Comment by cyberscribe** [comment]
No, that does not matter. Make sure you have created a V2 Checkbox captcha, not any other kind.

**Comment by MichaelPfleger** [comment]
Thank you, i think the issue was that i did not register the httpS Domain too. my fault,
kind regards

**Comment by cyberscribe** [comment]
Glad it's working for you now.
