### ISSUE TITLE
Captcha showing in wrong language

### ISSUE THREAD

**Issue by Ozkovacs** [cyberscribe/login-recaptcha#17]
Hi there.
First, thanks for your plugin - it is a great piece of work!
I'm having only a small issue as follows.
I have my site set to "French Canadian" in the configuration.
When looking at your plugin's configuration page, I can see the Captcha in the right language.
However, when in the login or registration page, I see it in English.
I tried copying over the fr_FR pages renaming them to fr_CA, but it didn't help.

Would you have any idea?

Thanks a lot,
Zolt

**Comment by cyberscribe** [comment]
Hi Zolt,

There are two places where things are translated: WordPress, and the Google Captcha. In WordPress, if your site is set to French you should see the configuration page in French.

Both the captcha itself that shows up in the Admin and the one that shows up on the login page are controlled by Google Captcha. Here, Google will look at the language setting of the web browser to determine what language to use. So, if you are using a browser with the language set to English on a WordPress site set to French, you will see the Captcha in English and the site in French. Using a browser with the language set to French, both should appear in French.

Hopefully this helps!

Best,
Robert

**Comment by Ozkovacs** [comment]
Un gros merci!
Seems to be this simpme indeed!

Thanks for the fast response.  Really appreciated.


Le jeu. 18 juil. 2019 05:48, Robert Peake <notifications@github.com> a
écrit :

**Comment by cyberscribe** [comment]
de rien :)

**Comment by Ozkovacs** [comment]
Je me disais bien... 😀

En passant j'utilise Project Nami qui est WP qui roule sous MS SQL.  Ce
n'est vraiment pas tout les plugins qui marchent avec ça, mais le tien
marche très bien!  J'en suis bien content!  C'est juste pour un petit blog
personnel.

Merci encore.
 Olivier (Zolt)

Le jeu. 18 juil. 2019 06:46, Robert Peake <notifications@github.com> a
écrit :

> de rien :)
>

**Comment by cyberscribe** [comment]
Formidable. Bonne chance!
