### ISSUE TITLE
Latest update has broken CSS for /my-account

### ISSUE THREAD

**Issue by LaurenceMillward** [cyberscribe/login-recaptcha#20]
More of an FYI than anything, but i've had to disable this plugin due to the latest update. The CSS change in the update is clashing with the woocommerce "/my-account" pages when using a custom theme, causing them to look messy. Fonts, hyperlinks etc all got changed.

**Comment by cyberscribe** [comment]
Hi Laurence,

Sorry to hear this.

The actual css change was extremely minor, but also implemented some cache busting. I have quite a few sites running this plugin with WooCommerce, and they all look OK. That said, I don't know how you've customised your theme. 

So, it could be that the cache busting actually caused some much earlier changes to "kick in", or it's possible this could be unrelated. Seems unlikely this specific tiny change would cause such a huge change to the visuals, but again I don't know the details of your custom theme.

Anyway, sorry to hear it and if you do get to the bottom of why this happened I'd be curious to hear.

Best,
Robert
