### ISSUE TITLE
Not rendern in pages

### ISSUE THREAD

**Issue by kanishka5564** [cyberscribe/login-recaptcha#27]
Hi, I'm using this plugin (https://wordpress.org/plugins/login-recaptcha/) for my WordPress woo-commerce website. It is showing on my account page properly. But on other pages google Recaptcha was not rendered. Why this not rendered on other pages?

**Comment by cyberscribe** [comment]
Please post in the forum; someone may be able to help you there: https://wordpress.org/support/plugin/login-recaptcha/

Also see the FAQ as this is likely your problem: https://wordpress.org/plugins/login-recaptcha/#does%20this%20plugin%20add%20a%20captcha%20to%20custom%20forms%3F
