### ISSUE TITLE
I can easily bypass the I m not a robot verification..

### ISSUE THREAD

**Issue by NabarajDhungel01** [cyberscribe/login-recaptcha#31]
I can easily bypass the I m not a robot verification..

Steps to Reproduce :
1. Open the login page
2. In the Submit button (i.e input[type="submit" field , 
In the below input html tag, remove the disabled attribute to below:
BEFORE :
    ```
    <input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="Log In" disabled="disabled">
    ```
AFTER:
    ```
    <input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="Log In" >
    ```
          ) 
3. Bypass Successful

**Comment by cyberscribe** [comment]
The functionality is implemented server-side and does not depend on the enable/disable of the submit button. Please be sure you have configured the captcha settings correctly
