### ISSUE TITLE
Disabling Javascript with uBlock origin lets you login without doing the captcha

### ISSUE THREAD

**Issue by Stoxis** [cyberscribe/login-recaptcha#32]
Steps to reproduce
1. Enable this plugin
2. Download uBlock Origin
3. Disable Javascript
4. Go to the login page
5. Re-captcha doesn't appear
6. ???
7. Profit!

**Comment by cyberscribe** [comment]
If the plugin is properly configured, just because the captcha does not appear when javascript is blocked does not mean you can bypass the captcha checking and log in. The captcha checking happens on the back end.
