### ISSUE TITLE
Problems with removing the plugin

### ISSUE THREAD

**Issue by giblim** [cyberscribe/login-recaptcha#34]
I decided to remove the plugin from my site.
I removed the cookies from my browser.
Anyway the demand to check " I am not a robot" still shows up.

![FireShot Capture 606 - Log In ‹ Curano — WordPress - www curano eu](https://github.com/cyberscribe/login-recaptcha/assets/44395552/78c1a9a3-d74e-46fb-becf-812863718e05)

How to proceed ?
Thanks for help.

**Comment by cyberscribe** [comment]
The easiest way to ensure the plugin is not active is to remove the plugin directory from the filesystem

**Comment by giblim** [comment]
I don't see it in the filesystem:

[image: FireShot Capture 607 - plugins - Files - File Browser -
srv1047-files.hstgr.io.png]

**Comment by cyberscribe** [comment]
See: https://developer.wordpress.org/advanced-administration/upgrade/ftp/

**Comment by giblim** [comment]
Sorry, I can't understand this.
I don't need Filezilla FTP access to get into the filesystem.
I am using hpanel (it's like cpanel) and I have an entire access to all
files.
The plugin is not in wp-contents/plugins.

Here a test login (administrator):

RL     https://www.naraka.eu/chronos_y
ID      test-captcha
PW    ***@***.***$lBURXf6efwIzCo

If you like to check it out.

**Comment by cyberscribe** [comment]
If the plugin directory is not in your filesystem then none of the plugin code exists in your WordPress set up and it is impossible that the plugin is the problem. Good luck!

**Comment by giblim** [comment]
Okay, I'll check it out.
Thanks

**Comment by cyberscribe** [comment]
If it were me, I'd reboot :) Good luck!

**Comment by giblim** [comment]
Already done. I work on this since yesterday.
