### ISSUE TITLE
Extension for WP Registration form?

### ISSUE THREAD

**Issue by lukasz-yasecure** [cyberscribe/login-recaptcha#5]
Hey Robert, great work. Plugin works very well. Don't you think about preparing similar version for WP registration? Maybe there is some easy tip to use your plugin also for that registration form? Of course, there is no possibility to login for bot which registered but it's quite frustrating if you see ~100 fake registration per day :)

Best regards!
Lukasz

**Comment by cyberscribe** [comment]
Hi Lukasz -- thanks for the suggestion. If there is an easy way to extend the core functionality to new user registrations, I'd welcome a pull request that accomplishes this. Thanks again!
