### ISSUE TITLE
The ReCaptcha can be bypassed

### ISSUE THREAD

**Issue by jezevec10** [cyberscribe/login-recaptcha#6]
There is a check if a captcha response is present in the form submission:
https://github.com/cyberscribe/login-recaptcha/blob/e7c5976ec34339924ead8ad706f8532cbc92da4a/login-nocaptcha.php#L137
If it is not there, the function succeeds.

The attacker can create a brute force script that will not include `g-recaptcha-response` in the POST requests and it is like the catcha wouldn't be there.

Suggested fix:
The function should fail if the captcha response is missing.

**Comment by cyberscribe** [comment]
Thank you for reporting this. It has been resolved in [5037d50](https://github.com/cyberscribe/login-recaptcha/commit/5037d508806a135cd230b9143b84bc7adaa0fdc2) and will be pushed to the WordPress repository shortly.
